# Welcome to Jekyll!
#
title: Filip Marić
author: >#Filip Marić
# email: filip.maric@mail.com
description: >- # this means to ignore newlines until "baseurl:"
#  My personal web page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
- publications.md
- projects.md
- cv.md
#- posts.md

remote_theme: aterenin/minima-reboot
plugins:
  - jekyll-feed
  - jekyll-redirect-from

markdown: CommonMarkGhPages

sass:
    style: compressed
